# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create :username => "Natalia", :email => "natalia@test.com", :password => "test", :score => 35
User.create :username => "John", :email => "john@test.com", :password => "test", :score => 100
User.create :username => "Mary", :email => "mary@test.com", :password => "test", :score => 50
User.create :username => "Anna", :email => "anna@test.com", :password => "test", :score => 25
User.create :username => "Tom", :email => "tom@test.com", :password => "test", :score => 95
User.create :username => "Someone", :email => "someone@test.com", :password => "test", :score => 10

Course.create :title => "MARC hero", :description => "Learn to catalogue with Machine Readable Cataloging", :duration => "X hours", :level => "Beginner", :logo => "/assets/badge_id_3.png"
Course.create :title => "AACR2 hero", :description => "Learn to catalogue with the Anglo American Cataloguing Rules 2", :duration => "X hours", :level => "Beginner", :logo => "/assets/badge_id_2.png"
RDAheroCourse = Course.create :title => "RDA hero", :description => "Learn to catalogue with Resource Description and Access", :duration => "X hours", :level => "Beginner", :logo => "/assets/badge_id_1.png"

RDAheroCourse.lessons.create(:title => "What is WEMI?", :content => "<p>Functional Requirements for Bibliographic Records (<strong>FRBR</strong>) is a conceptual model published in 1998. It is important for this course because it is the theoretical framework for Resource Description and Access (<strong>RDA</strong>).</p><p>FRBR is based on entity-attribute-relationship (<strong>EAR</strong>) models such as the ones used in databases. Entities are things. Relationships are what show the links between entities. Both entities and relationships can have attributes [1].</p><p>FRBR distinguishes three groups of entities. This lesson concerns Group 1, “products of intellectual or artistic endeavour”. WEMI stands for Work, Expression, Manifestation and Item.</p><p>Have a look at the model and click “Submit” when you are ready to continue.</p><p>References: 1. <a href='http://www.worldcat.org/oclc/124074707' alt='Understanding FRBR on WorldCat' target='_blank'>Taylor (2007)</a>, p. 5</p>", :activity => "<img src='/assets/WEMI_colour.png' alt='WEMI model graphic' class='img-responsive img-center'><p>Works are a “distinct intellectual or artistic creation, abstract entity with no single material object one can point to”. Expressions are a “realization of a work in alpha-numeric, musical, or choreographic notation, sound, image, object, movement, etc.; or any combination of such forms”. Manifestations are a “physical embodiment of an expression of a work” and an item is “a single exemplar of a manifestation” [1].</p>", :solution => "Type here your answer", :hint => "", :points => 5, :order => 1)
WEMI2Lesson = RDAheroCourse.lessons.create(:title => "An example", :content => "<p>Now that you have learned about WEMI. Let's see an example. Click “Submit” when you are ready to continue.</p>", :activity => "<img src='/assets/WEMIwithexamples.png' alt='WEMI model graphic' class='img-responsive img-center'>", :solution => "Type here your answer", :hint => "", :points => 5, :order => 2)
RDAheroCourse.lessons.create(:title => "The new structure of RDA", :content => "<p>If you have used AACR2, you may notice a change of structure in RDA. The sections are now organised according to FRBR’s entities and relationships.</p><p>The chapters are also “no longer organised base on the International Standard for Bibliographic Description (ISBD) areas of description” [2], meaning relevant rules to a particular area may be found on different sections.</p><p>Instead chapters contain an overview of the element, an overview of sub-elements and other details.</p><p>Examine the sections on the RDA toolkit on the image, when you are ready to continue, click “Submit”.</p><p>References: 2. <a href='http://dx.doi.org/10.1080/01639370903203234' alt='Preparing Catalogers for RDA Training on Cataloging and Classification Quarterly' target='_blank'>Hitchens & Symons (2009)</a>, p. 698</p>", :activity => "<img src='/assets/RDAtoolkit.png' alt='RDA table of contents' class='img-responsive img-center'>", :solution => "Type here your answer", :hint => "", :points => 5, :order => 3)
RDAheroCourse.lessons.create(:title => "Compare AACR2 and RDA", :content => "<p>Can you identify which content of tables belongs to AACR2 and which one belongs to RDA?</p><p>Type a number into the field box and click on “Submit” when you have finished.</p>", :activity => "<img src='/assets/comparecontenttables.png' alt='Tables comparison' class='img-responsive img-center'>", :solution => "2", :hint => "Remember RDA is based on the FRBR model.", :points => 5, :order => 4)
RDAheroCourse.lessons.create(:title => "RDA titles", :content => "<p><strong>Title</strong> is described in RDA as “a word, character, or group of words and/or characters that names a resource or a work contained in it” [3]. It is possible for a resource to have more than one. The different types of titles have been categorized for the purpose of the resource description in RDA.<p><p>A <strong>“title proper”</strong> is a <strong>core element of the description</strong>. It is described as the “chief name of a resource” [3] in the RDA Toolkit and it does not include [3]:</p><ul><li>2.3.3 Parallel titles proper,</li><li>2.3.4 Other title information or</li><li>2.3.5 Parallel other title information</li></ul><p>So we will not discuss them in this section.</p><p>The title proper is <strong>transcribed as it appears</strong> and it is taken from the <strong>preferred source</strong> (see RDA 2.2.2) as indicated in <strong>RDA 1.7.1. General rules of transcription</strong>.</p><p>Transcribe the title proper (highlighted text) on the image.</p><p>References: 3. <a href='http://www.rdatoolkit.org/' alt='RDA Toolkit' target='_blank'>RDA Toolkit</a></p>", :activity => "<img src='/assets/catalogue_title_proper_highlighted.png' alt='Cover of book that needs to be catalogued.' class='img-responsive img-center'>", :solution => "A Game of Thrones", :hint => "A Game of Thrones", :points => 5, :order => 5)
RDATitleLastLesson = RDAheroCourse.lessons.create(:title => "More on titles", :content => "<p> You can read <strong>2.3.2.7. Recording the title proper</strong> for further information.</p><p>In AACR2 the title was transcribed as it was on the source, if there were any errors they could be corrected by the cataloguer by adding missing letters with square brackets, giving the correction in brackets or using “[sic]” [4].</p><p>In RDA the title is also transcribed as it appears on the source but any corrections are recorded in a note as a <strong>variant title</strong>. Have a look at the variant titles subsection.</p><p>References: 4. <a href='http://dx.doi.org/10.1080/01639370903203234' alt='Preparing Catalogers for RDA Training on Cataloging and Classification Quarterly' target='_blank'>Hitchens & Symons (2009)</a>, pp. 699-700</p><h2>Let's try some examples!</h2><p>Now that you understand title proper, can you transcribe the following titles?</p><p>Type the answer like so: “Title 1, Title 2”.</p>", :activity => "<img src='/assets/transcribe_titles.png' alt='Books to catalogue' class='img-responsive img-center'>", :solution => "The Hobbit or There and Back Again, The Fellowship of the Ring", :hint => "The Hobbit or There and Back Again, The Fellowship of the Ring", :points => 5, :order => 6)

RDAheroCourse.create_badge(:name => "RDA hero", :description => "Congratulations for completing the RDA course!", :criteria => "Completed RDA hero path.", :image => "/assets/RDA_badge.png")
WEMI2Lesson.create_badge(:name => "FRBR: WEMI basics", :description => "Congratulations for completing the WEMI lesson!", :criteria => "Completed the lessons and activities related to WEMI.", :image => "/assets/WEMI_basics.png")
RDATitleLastLesson.create_badge(:name => "RDA title", :description => "Congratulations for completing the RDA title lesson!", :criteria => "Completed the lessons and activities related to RDA title.", :image => "/assets/RDA_title_badge.png")

RDAheroCourse.save
WEMI2Lesson.save
RDATitleLastLesson.save

Achievement.create :user_id => 1, :badge_id => 1, :created_at => "2015-08-08 13:26:44", :updated_at => "2015-08-08 13:26:44"
Achievement.create :user_id => 1, :badge_id => 2, :created_at => "2015-08-08 13:26:44", :updated_at => "2015-08-08 13:26:44"
Achievement.create :user_id => 1, :badge_id => 3, :created_at => "2015-08-08 13:26:44", :updated_at => "2015-08-08 13:26:44"